### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-uocqd#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by KIET7UKE** [comment]
![Screenshot (1034)](https://user-images.githubusercontent.com/76551267/188662439-0ba7eb30-e121-45b8-8e53-c5b85432e474.png)
![Uploading Screenshot (1033).png…]()

**Comment by KIET7UKE** [comment]
![Screenshot (1033)](https://user-images.githubusercontent.com/76551267/188662947-d76160a7-c70e-48aa-b37c-e93b31e620be.png)
